// AUTO-GENERATED by scripts/generate-supported-carriers.mjs — do not edit by hand.
// Regenerated on every `npm run dev` / `npm run build` from whatever logo
// files are present in public/carriers/ (excluding default.svg, the fallback).
export const SUPPORTED_CARRIER_SLUGS: readonly string[] = ["aramex","australia-post","blue-dart","canada-post","correos","dhl","dpd","fedex","gls","japan-post","postnl","purolator","royal-mail","swiss-post","tnt","ups","usps"];
